version: '3.8'

services:

  postgres:
    image: postgres:14.2-alpine
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_ROOT_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DATABASE
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres

  app:
    image: 'docker-spring-boot-postgres:latest'
    depends_on:
      - postgres
    build:
      context: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgres:$POSTGRES_DOCKER_PORT/$POSTGRES_DATABASE",
        "spring.datasource.username" : "$POSTGRES_USER",
        "spring.datasource.password" : "$POSTGRES_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQL92Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.h2.console.settings.web-allow-others" : "true"
      }'
    volumes:
      - .m2:/root/.m2

volumes:
  db: